'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase';
import styles from './request-records.module.css';

export default function RequestRecordsPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(true); 
  const [step, setStep] = useState<'form' | 'preview' | 'sent'>('form');
  const [saving, setSaving] = useState(false);
  const [authorized, setAuthorized] = useState(false);
  const [notice, setNotice] = useState('');
  const [form, setForm] = useState({
    patientName: '',
    dentistName: '',
    clinicName: '',
    clinicEmail: '',
    clinicPhone: '',
    lastVisitDate: '',
    notes: '',
  });

  const supabase = createClient();

  useEffect(() => {
    async function checkAuth() {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        router.push('/login?redirect=/request-records');
      } else {
        setForm(f => ({ ...f, patientName: user.user_metadata?.full_name || '' }));
        setLoading(false);
      }
    }
    checkAuth();
  }, [router, supabase.auth]);

  const todayString = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  function handleChange(e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) {
    setForm({ ...form, [e.target.name]: e.target.value });
  }

  function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    setStep('preview');
  }

  async function handleSend() {
    setSaving(true);
    const { data: { user } } = await supabase.auth.getUser();

    const { data: createdRequest, error } = await supabase
      .from('ehi_requests')
      .insert({
        patient_id: user?.id,
        patient_name: form.patientName,
        dentist_name: form.dentistName,
        clinic_name: form.clinicName,
        clinic_email: form.clinicEmail,
        clinic_phone: form.clinicPhone,
        last_visit_date: form.lastVisitDate || null,
        notes: form.notes,
        status: 'sent'
      })
      .select('id')
      .single();

    if (!error && user?.id) {
      await supabase.from('patient_authorizations').insert({
        patient_id: user.id,
        authorization_type: 'record_request',
        legal_name: form.patientName,
        accepted_text: 'I authorize DentoGraph to help generate and track this dental record request.',
        metadata: { clinic_name: form.clinicName, dentist_name: form.dentistName },
      });
      await supabase.from('audit_logs').insert({
        actor_id: user.id,
        action: 'create_record_request',
        entity_type: 'ehi_request',
        entity_id: createdRequest?.id || user.id,
        metadata: { clinic_name: form.clinicName },
      });
    }

    if (error) {
      console.error('Error saving request:', error);
      setNotice('There was an error saving your request. Please try again.');
    } else {
      setNotice('');
      setStep('sent');
    }
    setSaving(false);
  }

  function handleCopy() {
    const letterText = generateLetterText();
    navigator.clipboard.writeText(letterText);
    setNotice('Letter copied to clipboard.');
  }

  function generateLetterText() {
    return `FORMAL REQUEST FOR ELECTRONIC HEALTH INFORMATION (EHI)
Patient Record Access Request

Date: ${todayString}

To: ${form.dentistName}
    ${form.clinicName}

From: ${form.patientName}

Dear ${form.dentistName},

I am writing to request a complete copy of my dental records in an electronic format where available.

Under federal law, patients generally have rights to request copies of their health records in an electronic format where available. Please let me know if you need additional information to verify my identity or process this request.

I am requesting the following records:
• All dental X-rays and radiographic images (in digital format — JPEG, PNG, or DICOM)
• All clinical notes and treatment plans
• All prescriptions and procedure codes (CDT codes)
• Any 3D scans or intraoral photographs

PREFERRED DELIVERY METHOD:
Please upload my records securely through DentoGraph, my patient health platform. You can do so instantly — with no account required — using this secure link:

[DentoGraph Secure Upload Portal Link]

This request is made in good faith. Please let me know if you need additional information to verify my identity or fulfill the request.

${form.notes ? `Additional Notes: ${form.notes}\n\n` : ''}Thank you for your prompt attention to this matter.

Sincerely,
${form.patientName}

---
This request was generated by DentoGraph (dentograph.us)
Patient-owned dental records platform`;
  }

  if (loading) {
    return (
      <div className={styles.page} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh' }}>
        <div style={{ textAlign: 'center' }}>
          <div className="spinner" style={{ marginBottom: '16px' }}></div>
          <p style={{ color: 'var(--text-secondary)' }}>Verifying clinical session...</p>
        </div>
      </div>
    );
  }

  if (step === 'sent') {
    return (
      <div className={styles.page}>
        <nav className="navbar">
          <img src="/dentograph-logo.png" alt="DentoGraph" style={{ width: '188px', height: 'auto' }} />
          <button onClick={() => router.push('/dashboard')} className="btn btn-secondary btn-sm">← Dashboard</button>
        </nav>
        <div className="container" style={{ maxWidth: '700px', paddingTop: '48px', textAlign: 'center' }}>
          <div style={{ width: '72px', height: '72px', margin: '0 auto 18px', borderRadius: '50%', background: '#dcfce7', color: '#166534', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '2rem', fontWeight: 900 }}>✓</div>
          <h1>Request Generated Successfully</h1>
          <p style={{ color: 'var(--text-secondary)', marginTop: '12px', lineHeight: 1.6 }}>
            Your formal EHI request letter has been generated. You can copy it and send it via email to your dentist, 
            or print it and bring it to the clinic in person.
          </p>
          <div className={styles.statusTracker} style={{ marginTop: '40px' }}>
            <div className={`${styles.statusStep} ${styles.statusStepActive}`}>Request Created</div>
            <div className={styles.statusStep}>Sent to Dentist</div>
            <div className={styles.statusStep}>Records Uploaded</div>
            <div className={styles.statusStep}>AI Analysis Ready</div>
          </div>
          <div style={{ marginTop: '32px', display: 'flex', gap: '12px', justifyContent: 'center' }}>
            <button onClick={() => setStep('preview')} className="btn btn-secondary">← View Letter Again</button>
            <button onClick={() => router.push('/dashboard')} className="btn btn-primary">Go to Dashboard →</button>
          </div>
        </div>
      </div>
    );
  }

  if (step === 'preview') {
    return (
      <div className={styles.page}>
        <nav className="navbar">
          <img src="/dentograph-logo.png" alt="DentoGraph" style={{ width: '188px', height: 'auto' }} />
          <button onClick={() => router.push('/dashboard')} className="btn btn-secondary btn-sm">← Dashboard</button>
        </nav>
        <div className="container" style={{ maxWidth: '750px', paddingTop: '32px', paddingBottom: '80px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
            <div>
              <span className="badge badge-accent">Step 2 of 2</span>
              <h1 style={{ marginTop: '8px' }}>Review Your Request</h1>
            </div>
            <button onClick={() => setStep('form')} className="btn btn-secondary btn-sm">← Edit Details</button>
          </div>

          {notice && (
            <div style={{ marginBottom: '16px', padding: '12px 14px', borderRadius: '12px', background: '#ecfeff', border: '1px solid #a5f3fc', color: '#155e75', fontWeight: 700 }}>
              {notice}
            </div>
          )}

          <div className={styles.previewCard}>
            <div className={styles.letterHead}>
              <div style={{ fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.1em', color: 'var(--text-muted)', fontWeight: 700 }}>
                Formal Request for Electronic Health Information (EHI)
              </div>
              <div style={{ fontSize: '0.8rem', color: 'var(--accent)', fontWeight: 600, marginTop: '4px' }}>
                Patient Record Access Request
              </div>
            </div>

            <div className={styles.letterBody}>
              <p><strong>Date:</strong> {todayString}</p>
              <p><strong>To:</strong> {form.dentistName}<br />{form.clinicName}</p>
              <p><strong>From:</strong> {form.patientName}</p>

              <p>Dear {form.dentistName},</p>

              <p>
                I am writing to request a complete copy of my dental records in an electronic format where available.
              </p>

              <div className={styles.letterCitation}>
                Patients generally have rights to request copies of health records. Response timing and delivery
                requirements can vary by situation and should be reviewed by the clinic.
              </div>

              <p>I am requesting the following records:</p>
              <ul style={{ marginLeft: '20px', marginBottom: '16px' }}>
                <li>All dental X-rays and radiographic images (in digital format)</li>
                <li>All clinical notes and treatment plans</li>
                <li>All prescriptions and procedure codes (CDT codes)</li>
                <li>Any 3D scans or intraoral photographs</li>
              </ul>

              <p><strong>Preferred Delivery Method:</strong></p>
              <p>
                Please upload my records securely through <strong>DentoGraph</strong>, my patient health platform. 
                You can do so instantly — with no account required — using a secure upload link I will provide.
              </p>

              {form.notes && <p><strong>Additional Notes:</strong> {form.notes}</p>}

              <p>
                This request is made in good faith. Please let me know if you need additional information to verify my identity or fulfill the request.
              </p>

              <p>Sincerely,<br /><strong>{form.patientName}</strong></p>
            </div>

            <div style={{ textAlign: 'center', padding: '16px', borderTop: '1px solid var(--border)', marginTop: '24px', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
              Generated by DentoGraph — dentograph.us
            </div>
          </div>

          <div className={styles.actions}>
            <button onClick={handleCopy} className="btn btn-secondary btn-lg" style={{ flex: 1 }}>
              Copy Letter Text
            </button>
            <button onClick={() => window.print()} className="btn btn-secondary btn-lg" style={{ flex: 1 }}>
              Print Letter
            </button>
            <button onClick={handleSend} className="btn btn-primary btn-lg" style={{ flex: 1 }} disabled={saving}>
              {saving ? 'Processing...' : 'Mark as Sent'}
            </button>
          </div>
        </div>
      </div>
    );
  }

  // Step: form
  return (
    <div className={styles.page}>
      <nav className="navbar">
        <img src="/dentograph-logo.png" alt="DentoGraph" style={{ width: '188px', height: 'auto' }} />
        <button onClick={() => router.push('/dashboard')} className="btn btn-secondary btn-sm">← Dashboard</button>
      </nav>

      <div className="container" style={{ maxWidth: '700px', paddingTop: '32px', paddingBottom: '80px' }}>
        <div className={styles.header}>
          <div style={{ width: '56px', height: '56px', borderRadius: '16px', background: '#e0f2fe', color: '#0369a1', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 900 }}>REQ</div>
          <div>
            <span className="badge badge-accent">Step 1 of 2</span>
            <h1>Request Your Records</h1>
            <p style={{ color: 'var(--text-secondary)', marginTop: '4px' }}>
              Generate a clear request for dental records from a previous clinic.
            </p>
          </div>
        </div>

        <form onSubmit={handleGenerate}>
          <div className="card" style={{ padding: '32px', marginBottom: '24px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px', paddingBottom: '16px', borderBottom: '1px solid var(--border)' }}>
              <div style={{ width: '32px', height: '32px', borderRadius: '50%', background: 'var(--primary)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 700 }}>1</div>
              <div style={{ fontWeight: 700, fontSize: '1.1rem' }}>Patient Verification</div>
            </div>
            <div className={styles.formGrid}>
              <div className="form-group">
                <label className="label">Legal Full Name <span style={{ color: 'var(--red)' }}>*</span></label>
                <input name="patientName" className="input" placeholder="e.g. John Doe" value={form.patientName} onChange={handleChange} required />
              </div>
              <div className="form-group">
                <label className="label">Approximate Last Visit</label>
                <input name="lastVisitDate" type="date" className="input" value={form.lastVisitDate} onChange={handleChange} />
              </div>
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', margin: '32px 0 24px 0', paddingBottom: '16px', borderBottom: '1px solid var(--border)' }}>
              <div style={{ width: '32px', height: '32px', borderRadius: '50%', background: 'var(--primary)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 700 }}>2</div>
              <div style={{ fontWeight: 700, fontSize: '1.1rem' }}>National Provider Database Lookup</div>
            </div>
            
            <div style={{ background: '#f8fafc', padding: '16px', borderRadius: 'var(--radius-md)', border: '1px dashed var(--border)', marginBottom: '24px' }}>
              <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', margin: 0 }}>
                Enter your clinic details. DentoGraph will prepare a request you can send or track inside your account.
              </p>
            </div>

            <div className={styles.formGrid}>
              <div className="form-group">
                <label className="label">Attending Provider Name <span style={{ color: 'var(--red)' }}>*</span></label>
                <input name="dentistName" className="input" placeholder="e.g. Dr. Jane Smith, DDS" value={form.dentistName} onChange={handleChange} required />
              </div>
              <div className="form-group">
                <label className="label">Facility / Clinic Name <span style={{ color: 'var(--red)' }}>*</span></label>
                <input name="clinicName" className="input" placeholder="e.g. City Dental Associates" value={form.clinicName} onChange={handleChange} required />
              </div>
              <div className="form-group">
                <label className="label">Facility Email (For Digital Routing)</label>
                <input name="clinicEmail" type="email" className="input" placeholder="records@citydental.com" value={form.clinicEmail} onChange={handleChange} />
              </div>
              <div className="form-group">
                <label className="label">Facility Phone</label>
                <input name="clinicPhone" type="tel" className="input" placeholder="(555) 123-4567" value={form.clinicPhone} onChange={handleChange} />
              </div>
              <div className={`form-group ${styles.fullWidth}`}>
                <label className="label">Clinical Notes or Specific Requests</label>
                <textarea name="notes" className="input" rows={3} placeholder="e.g. I need my panoramic X-rays from my 2023 implant consultation." value={form.notes} onChange={handleChange} style={{ resize: 'vertical' }} />
              </div>
            </div>
          </div>

          <div className={styles.legalNote}>
            <strong>Authorization:</strong> DentoGraph prepares a record request based on the information you provide.
            Final clinic response timing and delivery may vary. This is not legal advice.
          </div>

          <label style={{ display: 'flex', gap: '10px', alignItems: 'flex-start', fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.5, marginTop: '18px' }}>
            <input type="checkbox" checked={authorized} onChange={e => setAuthorized(e.target.checked)} required style={{ marginTop: '3px' }} />
            <span>I authorize DentoGraph to generate this record request and store a timestamped authorization in my account.</span>
          </label>

          <button type="submit" className="btn btn-primary btn-lg" style={{ width: '100%', marginTop: '24px' }} disabled={!authorized}>
            Generate Record Request Letter →
          </button>
        </form>
      </div>
    </div>
  );
}
