'use client';
import type { DentalAnalysis } from '@/lib/schemas';
import { FileDown } from 'lucide-react';

interface EHIExportProps {
  findings: DentalAnalysis;
  recordId: string;
  recordType: string;
  dentistName?: string;
  clinicName?: string;
  visitDate?: string;
}

export default function EHIExportButton({ findings, recordId, recordType, dentistName, clinicName, visitDate }: EHIExportProps) {
  
  function handleExportPDF() {
    // Build a clean, printable HTML document
    const displayDate = visitDate
      ? new Date(visitDate).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
      : new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

    const findingsHTML = findings.findings.map((f, i) => `
      <tr>
        <td style="padding:8px;border:1px solid #ddd;">${f.tooth_number || 'General'}</td>
        <td style="padding:8px;border:1px solid #ddd;">${f.condition}</td>
        <td style="padding:8px;border:1px solid #ddd;">${(f.severity_score || 0) >= 7 ? 'High' : (f.severity_score || 0) >= 4 ? 'Moderate' : 'Routine'}</td>
        <td style="padding:8px;border:1px solid #ddd;">${f.severity_score || 'N/A'}/10</td>
        <td style="padding:8px;border:1px solid #ddd;">${f.explanation}</td>
        <td style="padding:8px;border:1px solid #ddd;">${f.cdt_codes?.map(c => c.code).join(', ') || '—'}</td>
        <td style="padding:8px;border:1px solid #ddd;">${f.timeframe || '—'}</td>
      </tr>
    `).join('');

    const html = `
<!DOCTYPE html>
<html>
<head>
  <title>DentoGraph Health Report — ${displayDate}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; color: #1a1a2e; padding: 40px; line-height: 1.6; }
    .header { text-align: center; padding-bottom: 24px; border-bottom: 3px solid #2563EB; margin-bottom: 32px; }
    .header h1 { font-size: 1.8rem; color: #2563EB; }
    .meta { display: flex; gap: 40px; margin-bottom: 32px; }
    .meta-item .label { font-size: 0.75rem; text-transform: uppercase; color: #94a3b8; font-weight: 700; }
    .meta-item .value { font-size: 1rem; font-weight: 600; margin-top: 2px; }
    .section { margin-bottom: 32px; }
    .section h2 { font-size: 1.2rem; color: #2563EB; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1px solid #e2e8f0; }
    .summary-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
    th { background: #f1f5f9; padding: 8px; border: 1px solid #ddd; text-align: left; font-weight: 700; font-size: 0.75rem; text-transform: uppercase; }
    .footer { margin-top: 48px; padding-top: 16px; border-top: 2px solid #e2e8f0; text-align: center; font-size: 0.8rem; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="header">
    <h1>DentoGraph — Clinical Health Report</h1>
    <p>HIPAA-Compliant Patient Record</p>
  </div>

  <div class="meta">
    <div class="meta-item">
      <div class="label">Visit Date</div>
      <div class="value">${displayDate}</div>
    </div>
    <div class="meta-item">
      <div class="label">Dentist Office</div>
      <div class="value">${clinicName || 'Verified Record'}</div>
    </div>
  </div>

  <div class="section">
    <h2>Health Summary</h2>
    <div class="summary-box">
      <strong>Patient Summary:</strong> ${findings.patient_summary}
    </div>
  </div>

  <div class="section">
    <h2>Clinical Findings</h2>
    <table>
      <thead>
        <tr>
          <th>Tooth</th><th>Condition</th><th>Status</th><th>Priority</th><th>Explanation</th><th>CDT Codes</th><th>Timeframe</th>
        </tr>
      </thead>
      <tbody>${findingsHTML}</tbody>
    </table>
  </div>

  <div class="footer">
    <p>Generated by DentoGraph (dentograph.us)</p>
    <p>Always consult your dental professional for clinical decisions.</p>
  </div>
</body>
</html>`;

    // Create a temporary hidden container for the PDF generation
    const element = document.createElement('div');
    element.innerHTML = html;
    element.style.position = 'absolute';
    element.style.left = '-9999px';
    document.body.appendChild(element);

    // Dynamically load html2pdf.js and trigger silent download
    const script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';
    script.onload = () => {
      // @ts-ignore
      window.html2pdf()
        .set({
          margin: 10,
          filename: `DentoGraph_Report_${recordId.slice(0, 8)}.pdf`,
          image: { type: 'jpeg', quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true },
          jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
        })
        .from(element)
        .save()
        .then(() => {
          document.body.removeChild(element);
        });
    };
    document.head.appendChild(script);
  }

  return (
    <>
      <button 
        onClick={handleExportPDF} 
        className="btn btn-secondary btn-sm" 
        style={{ border: 'none', background: '#f1f5f9', fontWeight: 700, fontSize: '0.75rem', color: '#0f172a', display: 'flex', alignItems: 'center', gap: '8px', height: '32px' }}
      >
        <FileDown size={14} /> Download Report
      </button>
    </>
  );
}
